#nullable enable

namespace Shared.GameDataTypes
{
    // Only the values referenced by the ported gameplay code (plus the hero bodies) are kept; numeric values match the original data.
    public enum CharacterType
    {
        None = 0,
        Spaceship_Boss = 9,
        Tenti = 27,
        IceAge_BossDireWolfChief = 43,
        IceAge_BossIceGolem = 44,
        Egypt_EliteScorpion = 62,
        Egypt_BossSphinx = 66,
        Egypt_BossRa = 69,
        Ignatia = 70,
        Summon_Egypt_Archer = 72,
        Alpha = 75,
        Troy_ElitePhalanx = 85,
        Troy_BossTrojanHorse = 91,
        Ketchapi = 98,
        Yoyo = 99,
        Dice = 100,
        ThreeKingdom_Dongzhuo = 103,
        Threekingdoms_BossZhugeliang = 150,
        Viking_BossLoki = 174,
        Viking_BossKraken = 175,
        Viking_BossGiantOctopus = 187,
        Viking_BossFreya = 189,
        Special_Gold_Goblin = 223,
        Special_Gem_Goblin = 224,
        Sengoku_EliteGhostWarrior = 236,
        Gum = 241,
        Sengoku_EliteWindGod = 262,
        Laika = 268,
        Susanoo_Summon_WindGod = 270,
        EarthGuardian_Elite_FixingMan = 280,
        Crusades_EasternEmpireShip = 338,
        Crusades_EasternEmpireShip_Collider = 339,
        Inca_BossMancoCapac = 373,
        Arabian_EliteGuardCaptain = 427,
        Arabian_EliteMagician2 = 428,
        Arabian_Warrior = 431,
        Arabian_EliteVeteranWarrior = 439,
        Western_Boss_MiningKing = 456,
        Western_Boss_WyattEarp = 459,
        Western_EliteGunslingerRider = 464,
        Western_EliteGunslingerRider_B = 465,
        Western_ShovelMiner = 473,
        Steampunk_Engineer = 496,
        Steampunk_Alchemist = 497,
        Steampunk_EliteClockworkGolem = 509,
        Steampunk_EliteSaintGermain = 511,
        Steampunk_EliteTeslaCoil = 512,
        WorldWar_Boss_JosephStalinHard = 560,
        WorldWar_Boss_AdolfHitler = 561,
        Mamba = 730,
        EraMix_Boss_Zhugeliang = 929,
        EraMix_Boss_Freya = 998,
        EarthGuardian_Boss_TrampHard2 = 1094,
        Undine = 1099,
    }
}
