#nullable enable

namespace Shared.GameDataTypes
{
    public enum ItemType
    {
        None = 0,
        Tenti = 1,
        Ignatia = 2,
        Alpha = 3,
        Yoyo = 4,
        Dice = 5,
        Ketchapi = 6,
        Gum = 7,
        Laika = 8,
        PredatorArmor = 9,
        PredatorGloves = 10,
        PredatorShoes = 11,
        PredatorNecklace = 12,
        PredatorRing = 13,
        InvaderArmor = 14,
        InvaderGloves = 15,
        InvaderShoes = 16,
        InvaderNecklace = 17,
        InvaderRing = 18,
        GuardianArmor = 19,
        GuardianGloves = 20,
        GuardianShoes = 21,
        GuardianNecklace = 22,
        GuardianRing = 23,
        AvengerArmor = 24,
        AvengerGloves = 25,
        AvengerShoes = 26,
        AvengerNecklace = 27,
        AvengerRing = 28,
        TimeRulerArmor = 29,
        TimeRulerGloves = 30,
        TimeRulerShoes = 31,
        TimeRulerNecklace = 32,
        TimeRulerRing = 33,
        EquipmentElementArmor = 52,
        EquipmentElementGloves = 53,
        EquipmentElementShoes = 54,
        EquipmentElementNecklace = 55,
        EquipmentElementRing = 56,
        RandomEquipmentReinforceTicket = 57,
        Gold = 66,
        Gem = 67,
        StarCandy = 68,
        SpecialDNA = 69,
        AccountExp = 70,
        Stamina = 71,
        ResurrectionCoin = 74,
        MainCharacterTicket = 76,
        SubCharacterTicket = 77,
        EquipmentMaterialArmor = 78,
        EquipmentMaterialGloves = 79,
        EquipmentMaterialShoes = 80,
        EquipmentMaterialNecklace = 81,
        EquipmentMaterialRing = 82,
        Mamba = 87,
        Undine = 103,
    }
}
