using UnityEngine;
using UnityEngine.SceneManagement;
using SamMul.GameClients.Stages.CombatSystems;
using SamMul.ObjectPools;

namespace SamMul.GameClients.Stages.AreaEffectObjects
{
    public enum AreaEffectType
    {
        Glutton,
        SpinBlade,
        DeathTouch,
        AmbushMonster,
        PlasmaDrill,
        TrapBomb,
        RuneTrap,
        DefensiveField,
        GymBall,
        Meteor,
        LavaReflectionObject,
        TentiSweep_Default,
        TentiSweep_Hina,
        TentiSweep_Bongjun,
        TentiSweepTranscendent_Default,
        TentiSweepTranscendent_Hina,
        TentiSweepTranscendent_Bongjun,
        TentiSweepVertical_Default,
        TentiSweepVertical_Hina,
        TentiSweepVertical_Bongjun,
        IceThreeLeapsBugPoison,
        IceGolemShockWave,
        PoisonousArea,
        IgnitionWave_Default,
        IgnitionWave_Siyeon,
        IgnitionWave_Bongjun,
        IgnitionWaveTranscend_Default,
        IgnitionWaveTranscend_Siyeon,
        IgnitionWaveTranscend_Bongjun,
        EgyptSnakeDruidSnakeReflectionObject,
        EgyptSphinxVerticalObject,
        AlphaGatlingHoming_Default,
        AlphaGatlingHoming_Magenta,
        RaAreaEffectObject,
        AresSpear,
        ZeusLightning,
        BloodRapier,
        BloodRapierTranscendent,
        BattleYoYo_Default,
        BattleYoYo_EggKim,
        BattleYoYoTranscendent_Default,
        BattleYoYoTranscendent_EggKim,
        DeployBattleYoYo_Default,
        DeployBattleYoYo_EggKim,
        LaserAreaEffect,
        ZhangjueLaser,
        ThreekingdomArcher,
        AxeBoomerang,
        VikingSmallAxe,
        VikingThunderHammer,
        VikingThunderWarriorLightning,
        FallingRock,
        FirePillar,
        ZhugeliangLaser,
        TrickWarriorSpear,
        LokiSpear,
        KrakenInkBall,
        MjolnirBoomerang,
        HomingProjectile,
        FreyaMagicCircle,
        OdinGungnir,
        LavaMachineReflectionObject,
        XxperManReflectionObject,
        XxperManLaser,
        BubbleGum_Default,
        BubbleGum_Spy,
        ChewingBag,
        KennyoSpinBeads,
        ShockBomb,
        BouncingClaw,
        IronFist,
        IronFistTranscendent,
        WindField,
        ShootingStar,
        ShootingStarExplosion,
        SusanooSpinBead,
        SusanooLightning,
        SolderManLaser,
        SolderManReflectionObject,
        IceDireWolfReflectionObject,
        IceThreeLeapsBugReflectionObject,
        EgyptSnakeDruidReflectionObject,
        ReflectionObject,
        DelayAreaEffectObject,
        DrLeeReflectionObject,
        CaptainMilitaryBoomerang,
        LavaCrossSplitObject,
        TrampReflectionCrossSplitObjet,
        EgyptSphinxReflectionObject,
        AssaultLeaderReflectionObject,
        SolderManSplitObject,
        HectorReflectiveShield,
        ZeusReflectionHomingObject,
        OdinReflectionHomingObject,
        ViracochaReflectionHomingObject,
        JangGakReflectionSpltObject,
        GreekGeneralReturningSpear,
        CaoCaoReflectionObject,
        JyyuReflectionObject,
        AxeLeaderReflectingAxe,
        AxeLeaderReturningAxe,
        DrHomingMissileObject,
        DrHomingSmallMissileObject,
        SunquanSplitObject,
        SunquanReflectionObject,
        ZhugeliangReflectionObject,
        DongZhuoReflectionProjectileObject,
        TrickWarriorReflectionObject,
        LokiReflectionObject,
        PoisonMachinePoisonousAreaEffect,
        PoisonMachineHomingProjectile,
        MitsuhideReflectionObject,
        RanmaruReflectionObject,
        KojiroReflectionObject,
        KennyoSplitingProjectile,
        IeyasuReflectionObject,
        IeyasuSplitObject,
        SusanooBeadObject,
        ThorReflectionObject,
        FreyaReflectionObject,
        TornadoObject,
        PoisonPotionObject,
        EasternEmpireSplitObject,
        EasternEmpireReflectionObject,
        CrusadesCaptainBoomerangObject,
        HenriIIArrowObject,
        HenriIISandAreaEffect,
        HenriIIMaceObject,
        AlAshrafKhalilSplitObject,
        AlAshrafKhalilReflectionObject,
        SuperSolderBoomerangObject,
        RailGunReflectionObjet,
        RailGunSplitObject,
        ExplosionAreaEffect,
        ThunderboltReflectionObject,
        HernandoReflectionObject,
        AlmagroSplitObject,
        TupacAmaruSandMakeObject,
        GonzaloPizarroReflectionObject,
        Carlos1ReflectionObject,
        IntiTentacleObject,
        SuppressionCaptainReflectionObject,
        DrKooReflectionObject,
        ValorRangerReflectionObject,
        ValorRangerSplitObject,
        SpaceShipIceObject,
        SpaceShipTranscendentIceObject,
        SpaceShipIceGroup,
        LavaMachineHardBoomerangObject,
        DrKimSplitObject,
        GenieSandHomingObject,
        WitchQueenSplitObject,
        BlackCyclopsSplitObject,
        HarunAlRashidBoomerangObject,
        PeribanouSplitObject,
        SchaibarReflectionObject,
        DynamiteAreaEffectObject,
        MiningKingHomingSplitObject,
        GoldReflectionObject,
        WesternBigBulletReflectionObject,
        WyattEarpReflectionSplitObject,
        TrampHardReflectionObject,
        TrampHardSplitObject,
        DrLeeHardHomingReflectionObject,
        CaptainLoveDashReflectionObject,
        CaptainLoveSectorReflectionObject,
        JesseJameReflectionHomingBoomerangObject,
        JesseJameBoomerangObject,
        HeadMinerHardSplitObject,
        KidSplitReflectionObject,
        KidReflectionObject,
        WatchManDollReflectionObject,
        JamesWattReflectionObject,
        AbandoneSpecimenSpinAreaEffect,
        PoisonBall,
        NicolasFlamelReflectionObject,
        NicolasFlamelSpinObject,
        BattleGolemBoomerangObject,
        SpecialOperationSoldierReflectionObject,
        LeaderBHardReflectionObject,
        LeaderBHardSplitObject,
        WilhelmIIReflectionObject,
        PhilippePetainSpinObject,
        ErnestKingReflectionObject,
        JosephStalinReflectionObject,
        JosephStalinSplitObject,
        XxperManHardSplitObject,
        XxperManHardSpinObject,
        XxperManHardReflectionObject,
        WaffenSSReflectionObject,
        AdolfHitlerReflectionObject,
        ShootingChampionSplitObject,
        WeightliftingGiantReflectionObject,
        GloryStatueReflectionObject,
        BeggarKingReflectionObject,
        DriverReflectionHomingBoomerangObject,
        InvestmentKingSpinObject,
        InvestmentKingCircleBoomerangObject,
        SnaepCattSplitObject,
        BeggarKingReflectionPoisonousAreaEffectObject,
        DriverReflectionObject,
        MileJackReflectionObject,
        MileJackReflectionSmallObject,
        SuppressionCaptainSpinObject,
        SolderManHardSpinObject,
        DiagonalProjectileCreateObject,
        DancingTriangleObject,
        SpaceHunterReflectionHomingObject,
        MushroomHeadReflectionObject,
        GrassEatingFlowerReflectionObject,
        GrassEatingFlowerSpinObject,
        FirstMateReflectionObject,
        EnchantingGlowNormalAreaEffectObject,
        EnchantingGlowBodyObject,
        StageMeteorAreaEffectObject,
        StageLightningAreaEffectObject,
        StageSandAreaEffectObject,
        StageIceAreaEffectObject,
        HackedRobotSpinObject,
        HackedRobotReflectionObject,
        FirstMateHardReflectionHomingObject,
        PepperAssaultTrooperBoomerangObject,
        PepperAssaultExplosiveObject,
        PirateCaptainReflectionObject,
        EramixMammothChiefReflectionObject,
        ThreeLeapsBugPoisonHomingObject,
        PhilippePetainSplitObject,
        EraMixWilhelmIISplitObject,
        EraMixAnubisMaskSplitObject,
        EraMixJosephStalinSplitObject,
        EraMixJosephStalinReflectionHomingObject,
        SearchLeaderHardSpinObject,
        CaptainMilitaryHardReflectionHomingBoomerangObject,
        CaptainMilitaryHardSplitObject,
        EraMixBenitoMussoliniReflectionObject,
        EraMixBenitoMussoliniSpinObject,
        EraMixSnakeDruidReflectionObject,
        EraMixHochmeisterRedReflectionObject,
        DrBinHardReflectionObject,
        TestReflectionObject,
        TestSplitObject,
        TestSpinMoveObject,
        TestReflectionHomingObject,
        TestReflectionHomingBoomerangObject,
        EraMixHectorReflectionObject,
        EraMixHectorSpinMoveObject,
        EraMixCrusadesReflectionHomingBoomerangObject,
        EraMixCrusadesReflectionObject,
        EraMixRichardISplitObject,
        EraMixRichardIReflectionHomingObject,
        EraMixAlAshrafKhalilBoomerangObject,
        TestBoomerangObject,
        SplitObject,
        EraMixZeusSpecialReflectionHomingObject,
        ReflectionSplitObject,
        LightningMachineHardHomingSplitSpinMoveObject,
        SpinMoveObject,
        ReflectionHomingObject,
        SpecialOperationsSoldierHardReflectionHomingObject,
        MonsterInfinitySpinBladeObject,
        EraMixGuanyuLightningCreateObject,
        EraMixMileJackReflectionFireSplitObject,
        ReflectionHomingBoomerangObject,
        ReflectionMultiHitObject,
        HomingSplitObject,
        ReflectionHomingSplitObject,
        LandWhaleBasicWhaleObject,
        LandWhaleTranscendentWhaleObject,
        LandWhaleTranscendentFireObject,
        WoodTentacleObject,
        EraMixKojiroSplitToReflectionObject,
        StickySlimeNormalObject_Default,
        StickySlimeNormalObject_Bongjun,
        StickySlimeTranscendentObject_Default,
        StickySlimeTranscendentObject_Bongjun,
        ReflectionSplitSpinMoveObjectAreaEffectObject,
        SpinMoveMultiHitObject,
        IntiTentacleCreateObject,
        WoodTentacleCreateObject,
        SplitReflectionObject,
        DropStoneCreateObject,   
        DiesWithOwnerAreaEffectObject,
        LightningCreateObject,
        EraMixGenieReflectionFollowUpObject,
        GumSpecialMine,
        GumSpecialMineSlowAreaEffect,
        GumSupportFireAreaEffect,
    }

    /// <summary>
    /// 장판 효과를 구현하는 추상화클래스
    /// </summary>
    public abstract class AreaEffectObjectBase : MonoBehaviour, IPoolible<AreaEffectType>
    {
        /// <summary>
        /// 오브젝트가 유효한지 여부. <c>false</c>가 되면, 스테이지에서 제거된다.
        /// </summary>
        public abstract bool IsAlive { get; }
        public AreaEffectType AreaEffectObjectType { get; private set; }

        private AllianceType _alliance;
        public AllianceType Alliance => _alliance;

        /// <summary>
        /// 오브젝트 풀링 시스템에서 처음 할당될 때 공용 리소스들을 초기화합니다.
        /// 재활용되며 사용되는 시점에 인스턴스를 초기화하는 함수는 <see cref="InitializeBase"/> 입니다.
        /// </summary>
        /// <remarks>
        /// <see cref="AreaEffectObjectBase"/>를 상속받는 구체화클래스에는 모두 `AllocateSharedResourcesFor{자신클래스이름}(파라미터)`으로 초기화 코드를 만들고,
        /// 해당 초기화 코드의 상단에서 부모클래스의 `AllocateSharedResources{부모클래스}(파라미터)`를 호출해주세요.
        /// 유니티 MonoBehaviour시스템 내에서 생성자를 사용할 수 없으므로, 이와 같은 방법으로 자원 관리합니다.
        /// </remarks>
        protected void AllocateSharedResourcesForBase(AreaEffectType type)
        {
            AreaEffectObjectType = type;

            this.gameObject.layer = LayerMask.NameToLayer("Projectile");
        }

        /// <remarks>
        /// <see cref="AreaEffectObjectBase"/>를 상속받는 구체화클래스에는 모두 `Initialize{자신클래스이름}(파라미터)`으로 초기화 코드를 만들고,
        /// 해당 초기화 코드의 상단에서 부모클래스의 `Initialize{부모클래스}(파라미터)`를 호출해주세요.
        /// 유니티 MonoBehaviour시스템 내에서 생성자를 사용할 수 없으므로, 이와 같은 방법으로 초기화 체이닝을 구현합니다.
        /// </remarks>
        protected void InitializeAreaObject(AllianceType alliance)
        {
            _alliance = alliance;
        }

        public abstract void UpdateLogic(Stage stage, float deltaTime);

        #region IPoolible interfaces
        Scene IPoolible<AreaEffectType>.RelatedScene => this.gameObject.scene;

        AreaEffectType IPoolible<AreaEffectType>.PoolKey => AreaEffectObjectType;

        public virtual void PuttingBackToPool()
        {
        }
        #endregion 
    }
}
